[package]
name = "piaprox"
version = "0.1.0"
description = "Simple Pi Approximator"
edition = "2021"

[dependencies]
bigdecimal = "0.4.3"
clap = { version = "4.5.4", features = ["derive"] }
rug = "1.24.1"
rust_decimal = "1.35.0"
rust_decimal_macros = "1.34.2"
